### ISSUE TITLE
Responses in the discussion sections are difficult to read

### ISSUE THREAD

**Issue by Caustint** [HGVSnomenclature/hgvs-nomenclature#103]
I find the answers to the "Discussion" questions on the recommendation pages useful, however they are difficult to read in the new format with horizontal scroll bar (as an example, see the bottom of this page: https://hgvs-nomenclature.org/en/latest/recommendations/DNA/repeated/). Can you just make the font size smaller and wrap the text?

**Comment by ifokkema** [comment]
Closed by #120.
