### ISSUE TITLE
Fix admonition indentation

### ISSUE THREAD

**Issue by reece** [HGVSnomenclature/hgvs-nomenclature#106]
When fixing list indentation, admonitions were excessively indented, causing them to be treated as code.

**Comment by ifokkema** [comment]
Does this include the current rendering issues on the DNA/deletion page? Indeed, increased indentation led to errors on that page, but there are also issues with the backticks. I was running through some pages, making some fixes related to backticks, but I'll leave that page alone for now.

**Comment by ifokkema** [comment]
Closed by #120.
