### ISSUE TITLE
Protein insertion page lists incorrect (?) example

### ISSUE THREAD

**Issue by ifokkema** [HGVSnomenclature/hgvs-nomenclature#110]
The protein insertion page lists the following examples:

-----

`NP_003997.1:p.(Ser332_Ser333insX[1])`: the insertion of an unknown amino acid ('insX[1]') between amino acids Ser332 and Ser333
**NOTE**: the IUPAC code for an unknown amino acid is 'X' (see Standards). Note that in the past 'X' has been used to indicate a translation termination codon.
`NP_003997.1:p.(Val582_Asn583insX[5])` (alternatively `NP_003997.1:p.(Val582_Asn583insXXXXX))`: the insertion of 5 unknown amino acids (insX[5]) between amino acids Val582 and Asn583

-----

If `insX[5]` can be rewritten as `insXXXXX`, why then does `insX[1]` require the `[1]` at all? I believe the example is incorrect, and should be rewritten as `insX`.

**Comment by jtdendunnen** [comment]
correct, you spotted an error. I suggested a change. 'insX[1]' should not be used, this is 'insX'.
