### ISSUE TITLE
RNA repeat page lists incorrect (?) example

### ISSUE THREAD

**Issue by ifokkema** [HGVSnomenclature/hgvs-nomenclature#113]
On the [DNA repeat page](https://hgvs-nomenclature.org/en/latest/recommendations/DNA/repeated/) it is stated that coding transcripts can only have repeat units with a length divisible by three;

> exception: using a coding DNA reference sequence ("c." description) a Repeated sequence variant description can be used only for repeat units with a length which is a multiple of 3

This would then logically also apply to a coding RNA reference sequence. However, the [RNA repeat page](https://hgvs-nomenclature.org/en/latest/recommendations/RNA/repeated/) lists as the first example `r.-124\_-123[14]` and the alternative `r.-124ug[14]`. This can't be correct then; the negative position indicates this is a coding RNA reference sequence, so "ug" can't be a valid repeat sequence.

**Comment by jfjlaros** [comment]
I guess the intent behind this exception is to prevent certain types of repeats in coding DNA, not in `c.` descriptions as a whole. With this interpretation, the `r.` description in the 5' UTR would be admissible.

By the way, we are working on a new proposal for repeats in which we propose to drop this exception.

**Comment by ifokkema** [comment]
@jtdendunnen This hasn't passed community consultation and/or the HVNC committee yet, right? According to the current docs, a community is being prepared. I assume that's what Jeroen and you are talking about. In that case, I guess I'll leave this as is until the new guidelines are out. It makes little sense to "correct" something and have to change it later again.
