### ISSUE TITLE
Differences between local render and production website

### ISSUE THREAD

**Issue by ifokkema** [HGVSnomenclature/hgvs-nomenclature#126]
I've noticed differences in rendering of Q&As locally with my RTD install compared to the live site.
E.g.: https://hgvs-nomenclature.org/stable/recommendations/general shows a simple UL while locally, I have proper markup on the `main` branch.
![Screenshot_2024-01-09_21-47-01](https://github.com/HGVSnomenclature/hgvs-nomenclature/assets/11665018/53ddcbc8-0d63-4ecc-8aa8-b8b8325d3fcd)

On other pages, the rendering is affected in a different way. For example, the [DNA substitution](https://hgvs-nomenclature.org/stable/recommendations/DNA/substitution) page.
![Screenshot_2024-01-09_21-51-01](https://github.com/HGVSnomenclature/hgvs-nomenclature/assets/11665018/a65f4af2-8d3f-40d7-bb0b-395d510caba6)

@reece do you have any clues? Is maybe the website not running the latest `main` branch at `/stable`, or am I missing something else?

**Comment by reece** [comment]
Yes, your suspicion at the end is correct: stable is the most recent version that is associated with a branch or tag that looks like semantic version. There is a 21.0 branch that I created as part of #124, but it's currently behind main that we're using for development.

All of this merits some discussion about how we envision developing, perhaps concurrently, on patch, minor, and major releases.

**Comment by reece** [comment]
@ifokkema : I think we got to the bottom of this. I'm closing, but please reopen if you think issues remain.

**Comment by ifokkema** [comment]
Ah, all clear, thank you! I guess I should have had a better look at the available versions in the list. We'd need a release guideline that explains what steps to take (including a `git tag`) to release a new version and update the website, indeed. It could even be included in the general repository `README.md`, I guess?
