### ISSUE TITLE
Fix the 404 page

### ISSUE THREAD

**Issue by ifokkema** [HGVSnomenclature/hgvs-nomenclature#132]
The 404 page ([example](https://hgvs-nomenclature.org/test)) includes part of the template, but that doesn't render well because stylesheets aren't loaded. I couldn't quickly find the code responsible for it, but perhaps you know from the top of your head, @reece?

**Comment by reece** [comment]
That's interesting -- it loads fine for me. Here's a shot from an incognito window:

![image](https://github.com/HGVSnomenclature/hgvs-nomenclature/assets/109453/f848422c-9411-494a-8778-a349f725293b)

From your description, I guess that you're seeing something less pretty.

Also, we can customize the 404 page if we want.

**Comment by ifokkema** [comment]
Ah, the new redirect has fixed it! `/test` now becomes `/stable/test`, and then, all stylesheets load. I've tried other URLs as well, and it seems to work now. Closing.
