### ISSUE TITLE
Double-check example on the DNA/substitution page.

### ISSUE THREAD

**Issue by ifokkema** [HGVSnomenclature/hgvs-nomenclature#135]
The [DNA/substitution page](https://hgvs-nomenclature.org/stable/recommendations/DNA/substitution/) lists the following question and answer:

> "How can I shorten the descriptions of SNPs in a manuscript?"
    Publications reporting linkage or association studies often use a range of different markers/SNPs. Such publications should contain at least once an **unequivocal description of all markers** used linking them to a reference sequence, preferably a genomic reference sequence. When this has been done, simplified descriptions can be used like
    - **NM_004006.1 3G>T**, using a GenBank coding DNA reference sequence
    - **GJB2 76A>C**, using a HGNC-approved gene symbol as reference
    - **rs2306220 T>C**, using a [dbSNP-identifier](http://www.ncbi.nlm.nih.gov/SNP) as a reference
    - **DXS1219 CA[18];[21]** (or AFM297yd1 CA[18];[21]), using a marker DXS1219 (AFM297yd1) as reference

Shouldn't the top two suggestions be `NM_004006.1:c.3G>T` and `GJB2:c.76A>C`, respectively? Should we really recommend notations without prefixes?

**Comment by jfjlaros** [comment]
Although this does not answer the question (the description is not short), my top suggestion would be:

`NC_000023.11(NM_004006.3):c.3G>T`,

as it conveys both the reference sequence used to find the variant in the first place, as well as a user friendly projection on the transcript of interest.

I would discourage using a bare transcript identifier as a reference, unless this reference was used to call the variant in the first place. There are multiple issues when converting to and from these reference sequences, some of which cannot be solved by mapping or using MANE transcripts.

The other three suggestions I do not recognise as valid HGVS descriptions as they violate the following rule:

> [a sequence identifier must only ever identify one reference sequence, and the sequence referred to by a sequence identifier may not be deleted or changed](https://hgvs-nomenclature.org/stable/background/refseq)

**Comment by ifokkema** [comment]
> Although this does not answer the question (the description is not short), my top suggestion would be:
> 
> `NC_000023.11(NM_004006.3):c.3G>T`,

I'm afraid this is a completely different subject, as this would require a significant part of the HGVS nomenclature documentation to be adapted, and, most importantly, we need to figure out this discussion: https://github.com/HGVSnomenclature/hgvs-nomenclature/discussions/4


> The other three suggestions I do not recognise as valid HGVS descriptions as they violate the following rule:
> 
> > [a sequence identifier must only ever identify one reference sequence, and the sequence referred to by a sequence identifier may not be deleted or changed](https://hgvs-nomenclature.org/stable/background/refseq)

The Q&A that I copied here is about shortening descriptions where the reference sequence has already been mentioned elsewhere in the text (for tables, for instance). So there is already a reference sequence defined; it's just not connected to the variant description everywhere. This is, as far as I understand, and as the answer shows, acceptable. The question is just whether I should add the prefix there, because it's removed and I don't think removing the `c.` is a good idea, ever.

**Comment by jfjlaros** [comment]
> we need to figure out this discussion: #4

Agreed.

> The Q&A that I copied here is about shortening descriptions

The answer could be that there are no possibilities for this within the HGVS nomenclature. I would not mention these seemingly random suggestions at all.

**Comment by jtdendunnen** [comment]
Regarding Jeroen's question, please note this part:

"Such publications should contain at least once an unequivocal 
description of all markers used linking them to a reference sequence, 
preferably a genomic reference sequence."

So based on this, whatever description is used after this, a correct 
HGVS description will be in the paper. I therefore think this Q&A is OK.

However, when we think the example is debatable, I suggest we keep it 
simple and delete this Q&A.

Johan

**Comment by jfjlaros** [comment]
I have seen the paragraph you mentioned, so perhaps this is a bit of hair splitting on my part, but I think we should focus on the HGVS nomenclature in these pages. So removing non-HGVS suggestions of variant descriptions would be preferable in my opinion.

**Comment by ifokkema** [comment]
> So removing (all) non-HGVS compliant suggestions for variant descriptions would be preferable in my opinion.

I'm afraid that if `c.3G>T` _in the context of a reference sequence_ which is not directly physically attached to the variant description (i.e., `NM_004006.1:c.3G>T`) is no longer considered HGVS compliant, then half the examples in the documentation should be updated. I can't find any requirement to directly attach the reference sequence to all variant descriptions, and we often don't in the documentation. I just see the requirement that the variant descriptions should be in relation to a reference sequence. Not requiring the physical attachment and endless repetition of the reference sequence in texts allows providing the reference sequence in, e.g., the header of a table, and variant descriptions (`c.3G>T` etc) in the table body.

**Comment by jfjlaros** [comment]
I understand that it will become cumbersome if we have to use full descriptions in all of our examples. Perhaps we should distinguish between partial descriptions (like `c.123del`) and non-HGVS suggestions (like `DMD:123del`). My comments above apply to the latter.

**Comment by ifokkema** [comment]
I opened this issue, reporting the lack of prefixes. For some reason, the discussion became about reference sequences. My suggestion was to simply change `GJB2 76A>C` to `GJB2:c.76A>C` or, also fine, "_GJB2_ `c.76A>C`". I think we now agree that the latter is acceptable, right? Because in that case, I'll fix the page and close this issue.

**Comment by jfjlaros** [comment]
I would say that `c.76A>C` or even `76A>C` are acceptable partial descriptions in running text, provided the context is made clear and full descriptions are provided elsewhere. I would also have no problem with other solutions like a lookup table to name variants, as long as a link to the full descriptions can be made.

My problem with the given suggestions is that they hint to a hidden nomenclature; there seems to be a *reference*, alluded to by the phrase "using a ... reference", followed by an *HGVS-like variant notation*. Adding more syntax like coordinate systems and colons will only strengthen this idea.

Perhaps an adaptation of the first paragraph of this comment could serve as an answer to the original question, following Johan's suggestion is also fine with me.

**Comment by jtdendunnen** [comment]
the answer was, and remains, when the official HGVS description is 
given, anything description format may be used to "shorten the 
descriptions of SNPs in a manuscript".

**Comment by jfjlaros** [comment]
That sounds like a perfectly fine answer to me.
