### ISSUE TITLE
Review the first example on the Deletion page

### ISSUE THREAD

**Issue by rileygr** [HGVSnomenclature/hgvs-nomenclature#137]
The text/HGVS is inconsistent with the sequence example shown.  The deleted NT in the sequence shown is an A but the NT in the text and in the HGVS expression is a T:

- one nucleotide

-     NC_000023.11:g.33344591del: a deletion of the **T** at position g.33344591 in the sequence TGTG**A**TTCT to TGTG**_**TTCT: NOTE: the recommendation is not to describe the variant as NC_000023.11:g.33344591del**T**, 

If the deleted NT in the sequence is changed to T, it should be right-shifted.
https://hgvs-nomenclature.org/stable/recommendations/DNA/deletion/#examples

**Comment by jfjlaros** [comment]
I [confirmed this](https://mutalyzer.nl/normalizer/NC_000023.11:g.33344591del) and have suggested a change in the documentation.
