### ISSUE TITLE
Create a new release, to update the "stable" tag.

### ISSUE THREAD

**Issue by ifokkema** [HGVSnomenclature/hgvs-nomenclature#168]
During our last HVNC meeting, we couldn't easily locate the updated figure on the numbering page. This is due to the site's `stable` tag linking to the latest version and not to the `main` branch. That is fine, but that means we need more frequent updates if we want our updates to reach the public sooner. It would be good to discuss when to release and which of us can do so. I'm fine with having a go at it, but I don't want to do so without discussing it first with @reece and @ahwagner.

**Comment by reece** [comment]
@ifokkema Please see docs that I added in a PR. Want to try to release 21.0.3?

**Comment by ifokkema** [comment]
@reece That worked great! Thanks for the guidance!

**Comment by reece** [comment]
Terrific! Thanks for taking it on @ifokkema !
