### ISSUE TITLE
mkdocs fails to build the site

### ISSUE THREAD

**Issue by ifokkema** [HGVSnomenclature/hgvs-nomenclature#185]
It throws:
```
python -m mkdocs build --clean --site-dir $READTHEDOCS_OUTPUT/html --config-file mkdocs.yml
Error: [table-reader]: Incompatible plugin order: Define 'table-reader' after 'macros' in your mkdocs.yml.
```

However, the source code says:
https://github.com/HGVSnomenclature/hgvs-nomenclature/blob/53caacad73a4df91bcf2d57ef7bfe58be3e14807/mkdocs.yml#L23-L24

Swapping them makes my local build fail. So, we seem to be a bit stuck here. I am hoping @reece will know what to do :sweat_smile: It could be a version problem...?

**Comment by reece** [comment]
@ifokkema : this order is no longer relevant. I reversed it and fixed a minor bug in the `mkdocs-plugin-fix` branch. You can probably just merge that with what you're doing. 

Sorry about the trouble.

**Comment by ifokkema** [comment]
@reece 
> @ifokkema : this order is no longer relevant. I reversed it and fixed a minor bug in the `mkdocs-plugin-fix` branch. You can probably just merge that with what you're doing.

Ah, OK, cool! Could it be, though, that the changes haven't been pushed? That branch doesn't contain any recent commits.


> Sorry about the trouble.

No worries about the trouble! Maybe one day, I should go through all of the code so I understand better how mkdocs works and what your additional code does, so I can debug things myself as well without having to bother you.

**Comment by reece** [comment]
Sorry @ifokkema! 

A trivial PR is now in #187 .

**Comment by ifokkema** [comment]
Re-opening, as now my local `mkdocs` doesn't render the site. As indicated in the original report, the local `mkdocs` has the reverse requirement as RTD.

**Comment by ifokkema** [comment]
Rebuilding the virtual environment solves the problem. Keeping this open while we decide whether or not to update `requirements.txt`.
