### ISSUE TITLE
Create style guide

### ISSUE THREAD

**Issue by reece** [HGVSnomenclature/hgvs-nomenclature#23]
- [ ] Sequence and HGVS expression formatting, incl. highlighted text
- [ ] Review and reformat discussions
- [ ] Syntax block

**Comment by reece** [comment]
Changed the text formatting is worthwhile (IMO), but is also very involved. I'm going to reprioritize this effort below other content that is likely to be less controversial. Resume from existing branch when ready.

**Comment by reece** [comment]
Related: #46

**Comment by ifokkema** [comment]
What do we do with parts of variant descriptions? E.g.,:
"a deletion of nucleotides r.6 to r.8 in the reference sequence NM_004006.2." Should that be reformatted to:
"a deletion of nucleotides `r.6` to `r.8` in the reference sequence `NM_004006.2`."?

**Comment by reece** [comment]
It depends on the context.

When we're describing something that's typed or exchanged and subject to
parsing, I use monospace (``).
When the text is for a human, I drop the styling.

Since we're talking to a human in this sentence, I would probably prefer "a
deletion of nucleotides 6 to 8, inclusive, in the reference sequence
NM_004006.2".

-Reece
