### ISSUE TITLE
Menu provides no way of going back

### ISSUE THREAD

**Issue by ifokkema** [HGVSnomenclature/hgvs-nomenclature#51]
The menu on HGVS-nomenclature.org provides no way of going back.
E.g.,

- Open HGVS-nomenclature.org,
- Open the menu,
- Click on "Recommendations",
- You can now not go back to the main menu, you'll need to reload the page.
- Click an item, e.g., "DNA" -> "deletion".
- You can not use the menu to navigate to other parts of the site; you can only use it to navigate within the "DNA" menu tree.

Tested on FF 110 @ Ubuntu 22.04
![Screenshot_2023-07-04_08-16-05](https://github.com/HGVSnomenclature/hgvs-nomenclature/assets/11665018/2bf04687-f3a9-4edc-9544-d6eab1cd3d8a)

(we might need a new label for website fixes; for now, I used "documentation fix")

**Comment by reece** [comment]
This was fixed in 3fca4b7ca3bd9a0d75d7393ec4c0c676a2d53277
