### ISSUE TITLE
Correct an answer given on the DNA allele page.

### ISSUE THREAD

**Issue by ifokkema** [HGVSnomenclature/hgvs-nomenclature#58]
While correcting some mistakes in some examples, I ran into [this one](https://github.com/HGVSnomenclature/hgvs-nomenclature/blame/3f61cfd6f2df135da4212519f546334de93d42c8/docs/recommendations/DNA/alleles.md#L76):

> > I have a patient with hearing loss and variants in the GJB2 (c.35delG) and GJB6 (c.689_690insT) genes, how should I describe this? (Nancy Carson, Ottawa, Canada)

> The recommendation is to use the format GJB2:c.[35delG] GJB6:c.[689_690insT]. This uses standard HGVS descriptions and prevents confusion regarding which variant was found in which gene. Note it is essential that you also define the coding DNA reference sequence used. Another format, coping with this directly, is to describe the variants as NM_004004.2:c.[35delG] NM_006783.1:c.[689_690insT], i.e. using the Genbank reference sequences in stead of the HGNC approved Gene Symbol.

This must be very old; it can't seriously be the recommendation... I suggest:
- [x] Fix the question to include that these variants are _in trans_. That's not currently made clear and was only clarified during the discussion on this example.
- [x] Fixing the square brackets from the variant descriptions in this answer. These variants are _in trans_.
- [x] Changing the `NM_004004.2:c.35delG` to `NM_004004.2:c.35del`, as the `G` is redundant.
- [ ] ~~Perhaps changing the `NM_004004.2:c.35del` to either `NM_004004.2(GJB2):c.35del` or `GJB2(NM_004004.2):c.35del`; although I can't find whether this is official syntax, the first one has been used once elsewhere in the documentation, and the latter is in use in LOVD (as far as I remember, approved by Johan).~~ So this may require discussion. There was some talk in a recent HUGO Gene/Disease Specific Database Advisory Council meeting about this format, as a curator requested it.
- [x] Perhaps removing the descriptions without the reference sequences (e.g., `GJB2:c.35del`) to discourage its use. Or, otherwise, moving it to the back of the answer as a shorter alternative with the prerequisite to have defined the transcript reference sequence elsewhere.

**Comment by jtdendunnen** [comment]
Correct is NM_004004.5:c.[35del];NM_006783.4:c.[690dup]. I checked reference sequences and variant descriptions.
- square brackets can not be removed, these genes are on the same chromosome so on different alleles.
- agreed to use del, not delG
- NM_004004.2(GJB2):c.35del or GJB2(NM_004004.2):c.35del can not be used. HGVS does not allow these formats.

**Comment by ifokkema** [comment]
> Correct is NM_004004.5:c.[35del];NM_006783.4:c.[690dup]. I checked reference sequences and variant descriptions.
> * square brackets can not be removed, these genes are on the same chromosome so on different alleles.

Since `[` is the opening symbol for an allele, and `]` closes it, you mean: `[NM_004004.5:c.35del];[NM_006783.4:c.690dup]`. The last example on the allele page clearly shows that the refseq should be pulled into the `[...]` when it's not the same for all variants (which also makes the most sense).

> * NM_004004.2(GJB2):c.35del or GJB2(NM_004004.2):c.35del can not be used. HGVS does not allow these formats.

Are you sure? Because the [repeat syntax page](https://varnomen.hgvs.org/recommendations/DNA/variant/repeated/) clearly suggests `NM_023035.2(CACNA1A):c.6955CAG[26]` as an example.
Also, the [refseq page](https://varnomen.hgvs.org/bg-material/refseq/) lists the `NC_012920.1(MT-TL1)` format multiple times.

**Comment by jtdendunnen** [comment]
- "the syntax should be prefix [change1];[change2]."
Correct, this is the definition, but please note that the "prefix" is "c.". "NM_" is the reference sequence, not the prefix.

- when we do not accept NC_012920.1(MT-TL1) as exception, my preference is to not allow this format at all. We have never allowed a GeneSymbol in variant descriptions, so should not start with it now.

**Comment by jfjlaros** [comment]
I have always understood that `[var1;var2]` means that `var1` and `var2` are in phase and that `[var1];[var2]` means that they are in anti-phase. In this case, we seem to have two variants separated by approximately 30,000 nucleotides on the chromosome, described using different reference sequences without any claims about phasing.

Why not simply describe them as two separate variants?

**Comment by jtdendunnen** [comment]
"in phase" / "anti-phase", we use variants on one allele (in cis) or on different alleles (in trans).  We do not describe them as separate variants since we then lose the information that the variants are on the same chromosome, this is the basic purpose of "Allele" descriptions

**Comment by jfjlaros** [comment]
Thank you, this is in line with my understanding.

So because in this case we have no proof that the variants are on the same chromosome (molecule), we should not use a single allele description. Likewise, because we have no proof that the variants are on different chromosomes, we should not use a double allele description.

If a chromosomal reference sequence was used, perhaps we could describe the variants as follows ([source](https://hgvs-nomenclature.org/stable/recommendations/DNA/alleles/)):

`NC_000013.11:g.20189552del(;)20222791dup`

**Comment by jtdendunnen** [comment]
But, might not be clear from what is described on the web, there IS proof in this case since this was based on an example of di-genic inheritance of a disease and these variants were inherited from different parents so are on different chromosomes.

**Comment by jfjlaros** [comment]
Ah, that was not clear to me.

In this case, I would recommend a chromosomal description:

[`NC_000013.11:g.[20189552del;20222791dup]`](https://mutalyzer.nl/normalizer/NC_000013.11:g.%5B20189552del;20222791dup%5D)

alternatively, we can use projections to transcripts:

`NC_000013.11(NM_001110219.3):c.[690dup;*33148del]` (*GJB6*, MANE Select) and
`NC_000013.11(NM_004004.6):c.[-30031dup;35del]` (*GJB2*, MANE Select).

Also see [this example](https://hgvs-nomenclature.org/stable/recommendations/DNA/alleles/):

> `NC_000023.10:g.[30683643A>G;33038273T>G]`: one allele (X-chromosome) contains two different variants in two different genes, `g.30683643A>G` in the *GK* gene and `g.33038273T>G` in the *DMD* gene.

**Comment by jtdendunnen** [comment]
Regarding "NC_000013.11(NM_001110219.3):c.[690dup;*33148del] (GJB6, MANE Select) and NC_000013.11(NM_004004.6):c.[-30031dup;35del]" descriptions like this are not allowed (*33148del/-30031dup).

Regarding "I would recommend a chromosomal description NC_000013.11:g.[20189552del;20222791dup]", most users (clinical labs) prefer transcript-based variant descriptions.

**Comment by jfjlaros** [comment]
> descriptions like this are not allowed (*33148del/-30031dup).

As far as I know, these descriptions are allowed, what do you think is wrong with them?

> most users (clinical labs) prefer transcript-based variant descriptions.

I know, but then there is no way to convey information about the chromosome. As far as I know, using multiple reference sequences is not allowed in the HGVS nomenclature (apart from references to inserted sequences).

**Comment by jtdendunnen** [comment]
hgvs-nomenclature.org/stable/background/numbering/ has "transcript flanking : it is not allowed to describe variants in nucleotides beyond the boundaries of the reference sequence using the reference sequence"

"As far as I know, using multiple reference sequences is not allowed in the HGVS nomenclature"
It is you can describe a variant as NC_000023.11:g.32849777T>A NM_004006.3:c.137A>T r.137a>u p.Asp46Val

**Comment by jfjlaros** [comment]
> it is not allowed to describe variants in nucleotides beyond the boundaries of the reference sequence using the reference sequence

Because we use a chromosomal reference sequence, the positions used are not beyond its boundaries. If we would have used a transcript reference sequence (e.g., a bare `NM_`, `NR_`, etc.), I would have fully agreed with this statement.

>  It is you can describe a variant as NC_000023.11:g.32849777T>A NM_004006.3:c.137A>T r.137a>u p.Asp46Val

I would argue that those are different descriptions of the same variant, i.e., we can leave any of the parts out without losing information. I was specifically thinking of the suggestion you gave earlier:

`NM_001122.3:c.[var1];NM_445566.7:c.[var2]`,

where two reference sequences are used to describe one combination of variants.

I cannot find a definition of this syntax in the allele description pages, nor can I find an example of such a description in any of the nomenclature pages. I would also not be in favour of adding this syntax to the nomenclature because the variants are described using different reference sequences while the semicolon refers to a third, unmentioned, reference sequence.

**Comment by ifokkema** [comment]
I see I didn't respond to this anymore. I also just found this example on [the DNA allele page](https://hgvs-nomenclature.org/stable/recommendations/DNA/alleles/): `[M59228.1:g.250G>C;AF209160.1:g.572CA[(11_21)];Z11861.1:g.61T>C;Z16803.1:g.114A[(18_22)]]`. So this shows that, indeed, the reference sequence should be pulled *into* the square brackets when alleles with variants on different reference sequences are described. Therefore, `NM_004004.5:c.[35del];NM_006783.4:c.[690dup]` is invalid and `[NM_004004.5:c.35del];[NM_006783.4:c.690dup]` should be used. This also makes the most sense to me as it still allows nesting, while `NM_004004.5:c.[35del];NM_006783.4:c.[690dup]` does not.

**Comment by jfjlaros** [comment]
Again, I think we should not use multiple reference sequences in one allele description because it implies a third, unmentioned reference sequence.

I foresee difficulties in normalising variants using this syntax. For example, it is unclear how to normalise variants when the reference sequences used are close by or overlap.

**Comment by ifokkema** [comment]
> Again, I think we should not use multiple reference sequences in one allele description because it implies a third, unmentioned reference sequence.

What do you mean? Can you elaborate on this?


> I foresee difficulties in normalising variants using this syntax. For example, it is unclear how to normalise variants when the reference sequences used are close by or overlap.

Are you specifically thinking about variants that may normalize into one variant? I would argue that that type of normalization can only be done when the variants are described using one reference sequence. When multiple are used, the variants can only be normalized based on their respective reference sequences.

That said, we're digressing from the original reason for this post. We have to fix the variant descriptions on the page mentioned. Since it seems the used syntax is different from the currently accepted syntax, I will adjust the variant descriptions. If we want to change the rules on how the allele syntax is used in regard to different reference sequences, we should open a new issue.

**Comment by jfjlaros** [comment]
> Can you elaborate on this?

Sure. The semicolon in a single or multiple allele description (e.g., `[var1;var2]` or `[var1];[var2]`) indicates that the variants share a common reference, in this case a chromosome. In de syntax proposed above, the chromosome in question is never mentioned. This does not comply with the syntax rules explained on the nomenclature pages. Furthermore, by not mentioning this reference explicitly, we are limited in our options with regards to normalisation.

> Are you specifically thinking about variants that may normalize into one variant?

That is one case I am thinking of indeed, but also other cases like internally conflicting variant descriptions will be very hard to detect.

> I would argue that that type of normalization can only be done when the variants are described using one reference sequence.

That is exactly my point, we should mention this reference in the description.

> We have to fix the variant descriptions on the page mentioned.

I would be in favour of removing every example that does not comply to the syntax rules, which would also be an easy fix.
