### ISSUE TITLE
Update the syntax blocks; protein pages

### ISSUE THREAD

**Issue by ifokkema** [HGVSnomenclature/hgvs-nomenclature#63]
## Update the syntax blocks; protein pages
- Update all syntax blocks based on the new format as agreed upon on Oct 2nd, to be committed in branch `23-create-and-use-style-guide`.
- Separate issues are created for each category of nomenclature pages. This issue is for the protein pages.

### Details
- Related to #23.
- Create a new branch for this issue, and a separate PR, to be merged into `main`.
- Branch of off [23-create-and-use-style-guide](https://github.com/HGVSnomenclature/hgvs-nomenclature/tree/23-create-and-use-style-guide), or, if that has been merged into `main` already, branch of off [main](https://github.com/HGVSnomenclature/hgvs-nomenclature/tree/main).
- To keep handling the PRs as simple as possible, stick to only redesigning the syntax blocks. Other changes can be committed in other branches.

**Comment by reece** [comment]
Merged branch into 77-make-syntax-and-explanatory-text-consistent-across-dna-rna-aa to create consistency across efforts.
Closing issue and branch.
