### ISSUE TITLE
Sequence and HGVS expression formatting, including highlighted text; protein pages

### ISSUE THREAD

**Issue by ifokkema** [HGVSnomenclature/hgvs-nomenclature#66]
## Sequence and HGVS expression formatting, including highlighted text; protein pages
- Update all sequence and HGVS expression formatting as discussed on Oct 2nd.
- Separate issues are created for each category of nomenclature pages. This issue is for the protein pages.

### Details
- Related to #23.
- Create a new branch for this issue, and a separate PR, to be merged into `main`.
- Branch of off [23-create-and-use-style-guide](https://github.com/HGVSnomenclature/hgvs-nomenclature/tree/23-create-and-use-style-guide), or, if that has been merged into `main` already, branch of off [main](https://github.com/HGVSnomenclature/hgvs-nomenclature/tree/main).
- To keep handling the PRs as simple as possible, stick to only reformatting the sequence examples and HGVS expressions. Other changes can be committed in other branches.
- Simple HGVS expressions and sequences can just be enclosed in single backticks.
- More advanced expressions which require formatting, should be enclosed in `<code>` tags.
- HGVS expressions that should *not* be used (deliberate invalid examples), should use the `invalid` class. E.g., `<code class="invalid">g.1insA</code>`.
- Sequence changes are now commonly documented by mentioning two different sequences, where the user should then deduct from the formatting what sequence has changed. Simplify this and list only *one* sequence. You can use code classes `del` and `ins` to indicate deletions or insertions, respectively. Other changes are currently not strictly defined. You can use classes `spot1`, `spot2`, or `spot3` for different types of highlights. If you think a specific implementation should be discussed, tag the commit or the PR so we can standardize certain implementations.

**Comment by reece** [comment]
Working in #77 . Closing.
