### ISSUE TITLE
Review and reformat the discussions at the end of the pages; DNA pages

### ISSUE THREAD

**Issue by ifokkema** [HGVSnomenclature/hgvs-nomenclature#67]
## Review and reformat the discussions at the end of the pages; DNA pages
- Review all the discussions at the end of the page and make sure all formatting is standardized.
- Separate issues are created for each category of nomenclature pages. This issue is for the DNA pages.

### Details
- Related to #23.
- Create a new branch for this issue, and a separate PR, to be merged into `main`.
- Branch of off [23-create-and-use-style-guide](https://github.com/HGVSnomenclature/hgvs-nomenclature/tree/23-create-and-use-style-guide), or, if that has been merged into `main` already, branch of off [main](https://github.com/HGVSnomenclature/hgvs-nomenclature/tree/main).
- To keep handling the PRs as simple as possible, stick to only correcting and reformatting the discussions at the end of the pages. Other changes can be committed in other branches.
- Simple HGVS expressions and sequences can just be enclosed in single backticks.
- More advanced expressions which require formatting, should be enclosed in `<code>` tags.
- Note that errors could have been introduced due to the automated conversion process. Please check all notes carefully.
- Underscores in HGVS expressions are sometimes escaped, but they don't have to be.
- HGVS expressions that should *not* be used (deliberate invalid examples), should use the `invalid` class. E.g., `<code class="invalid">g.1insA</code>`.
- Sequence changes are now commonly documented by mentioning two different sequences, where the user should then deduct from the formatting what sequence has changed. Simplify this and list only *one* sequence. You can use code classes `del` and `ins` to indicate deletions or insertions, respectively. Other changes are currently not strictly defined. You can use classes `spot1`, `spot2`, or `spot3` for different types of highlights. If you think a specific implementation should be discussed, tag the commit or the PR so we can standardize certain implementations.

**Comment by reece** [comment]
I ended up taking on this work with #61, and it now appears in the same PR. I'm going to close this issue and continue in #61.
