### ISSUE TITLE
Fix styling in general.md

### ISSUE THREAD

**Issue by reece** [HGVSnomenclature/hgvs-nomenclature#84]
The questions in general.md are plain text. Highlight the question, perhaps with admonitions or definition lists.

**Comment by reece** [comment]
@ifokkema Good catch.

This issue was about styling the bullets and text.  I don't know why the admonitions weren't converted, but they need formatting like the others.

**Comment by ifokkema** [comment]
OK, no worries, I'll have a stab at it. I'll also include #103, #106, and #117, since they are all related. I have a few PRs open, by the way. When you have time, could you please have a look at them?
