### ISSUE TITLE
Check style for nested lists

### ISSUE THREAD

**Issue by ahwagner** [HGVSnomenclature/hgvs-nomenclature#98]
Differences between items at different levels of nested lists are too subtle to discern. It makes entries like [glossary:mutation](https://hgvs-nomenclature.org/en/latest/background/glossary/#:~:text=mutation%3A%20NOTE,a%20disease%20phenotype.) difficult to read.

**Comment by ahwagner** [comment]
I looked into this; relevant background in [this](https://github.com/mkdocs/mkdocs/issues/545) issue.

I propose that–for the short term–we address this with the `mdx_truly_sane_lists` extension as discussed in that thread, which will help us render historical content correctly without much additional work.

Long term, it might make sense to update our linter to capture markdown intents that are not multiples of 4, and address older lists.

**Comment by reece** [comment]
Merged in
